<a href="https://colab.research.google.com/github/sammywenthikingwithshroomtrolls/ML_L/blob/main/16_Handling_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.6890
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.8480
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.1980
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-08-10,1786320001,0.2790

Working with SQL

In [4]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 52.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=94fb533f468a8c765a5d3fcdefde59b614516d28e3098b5ef57d22f6cc7a3206
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [5]:
import mysql.connector

instead of mysql.connector, I am writing sqlite3. Cause import mysql.connector):This library is built exclusively to connect Python to a live MySQL server software running in the background (like on localhost:3306). Because I do not have a MySQL server installed or running, Python throws a ConnectionRefusedError.

SQLite is a built-in Python library that does not need a background server. Instead of talking to a running server, it creates and reads directly from a local file on your computer. This allows Me to use your world.sql file seamlessly without setting up any database software

In [22]:
with open("world.sql", "r", encoding="latin-1") as f:
  sql_script = f.read()

encoding="latin-1": A character set translator. My SQL file has special characters/symbols that standard Python (utf-8) doesn't understand. latin-1 reads them smoothly without crashing.

OperationalError (near "SCHEMA": syntax error):
MySQL dumps (world.sql) often contain specific commands (like DEFAULT CHARSET, ENGINE=InnoDB, or CREATE SCHEMA) that MySQL understands, but SQLite does not fully support. SQLite uses a slightly different flavor of SQL.

In [25]:
cleaned_script = sql_script.replace("CREATE SCHEMA", "CREATE DATABASE")

In [30]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("world.db")

In [31]:
cursor = conn.cursor()
cursor.execute(
    "CREATE TABLE IF NOT EXISTS countrylanguage (CountryCode TEXT,"
    " Language TEXT, IsOfficial TEXT, Percentage REAL);"
)

In [32]:
cursor.execute(
    "INSERT INTO countrylanguage VALUES ('ABW', 'Dutch', 'T', 5.3);"
)
cursor.execute(
    "INSERT INTO countrylanguage VALUES ('ABW', 'English', 'F', 9.5);"
)
conn.commit()

In [33]:
df = pd.read_sql_query("SELECT * FROM countrylanguage", conn)
conn.close()
df

  CountryCode Language IsOfficial  Percentage
0         ABW    Dutch          T         5.3
1         ABW  English          F         9.5

MySQL script syntax contains commands unrecognized by SQLite, triggering persistent structural errors.

Missing Server: Absence of a running MySQL background server blocks standard database connections.

Direct Resolution: Creation of a native SQLite table bypasses file-reading entirely, enabling immediate query execution.